import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });




export const metadata: Metadata = {
  title: "Five Up Review",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fr" className={`${inter.variable} dark`}>
      <body
        className="antialiased relative"
      >
        {children}
      </body>
    </html>
  );
}
