import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${inter.variable} dark`}>
      <body
        className="antialiased"
      >
         <div className=" absolute z-0  w-full h-[100px] rounded-full  top-0 left-0 blur-[120px] bg-primary/80"/>
        {children}
      </body>
    </html>
  );
}
